import React from 'react';
/** Query */
import TanStackQuery from '@/libs/TanStackQuery';
/** Type */
import type { Metadata } from 'next'
/** Font */
import { Inter } from 'next/font/google'
/** Style */
import '@/app/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackQuery>
          {children}
        </TanStackQuery>
      </body>
    </html>
  )
}

export default RootLayout;